### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by DavidMercier** [DavidMercier/PopIn#8]
"Thank you so much for launching the POPIN toolbox. When I clicked the button "RUN CALCULATIONS and PLOT", an error message showed, the content is "Wrong inputs for minimum and maximum depth values!". I tried several times even to use your original data and your filling-in parameters shown in the screenshot, this error message jumped out again. I was wondering what causes the error, can you give me some suggestion?
Thank you so much for your help in advance."
From Jiayu Sun (ResearchGate).
https://www.researchgate.net/publication/328530953_PopIn_Toolbox_documentation/comments

**Comment by DavidMercier** [comment]
Hi Jiayu,

On what Matlab version do you work?
Do you use the last version of the toolbox from Github repo?
Which env (MS, Linux, Mac)?
Thanks

**Comment by SUNLOVEERIN** [comment]
Hi, Dr. Mercier
> On what Matlab version do you work?
It's MATLAB 2020a academic version
> Do you use the last version of the toolbox from Github repo?
Nope, I downloaded the toolbox from your ResearchGate homepage.
> Which env (MS, Linux, Mac)?
MS

Thank you so much, I will try the latest version on Github first.

**Comment by DavidMercier** [comment]
Great, retry with the last toolbox version from Github.
Then if you still have a bug, can you tell me if it's only an error message from a dialog box or if you have somme errors on the command window ?
Thanks

**Comment by SUNLOVEERIN** [comment]
> Great, retry with the last toolbox version from Github.
> Then if you still have a bug, can you tell me if it's only an error message from a dialog box or if you have somme errors on the command window ?
> Thanks

Hi, Dr. Mercier
Thank you for your suggestion, it works now.  I noticed your raw data comes from MTS Nanoindenter, but we are using another one, named TI 950 TriboIndenter. Your raw data contains hardness (H) and reduced Young's modulus (E) corresponding to each depth and load, I was wondering this data derived from the test results directly or after calculating? Because  for our machine,  only one H and E can be obtained for each sample,

Thank you so much for youe reply in advance.
Sincerely

**Comment by DavidMercier** [comment]
Hi,
Good news.
In MTS, the software provides an .xls file with raw data (displacement, load and continuous stiffness in case of CSM mode) and calculated properties (E, H...). In case you have only raw data, it's not difficult to add by yourself a columun in .xls file with properties calculations or to write a small code in the toolbox to make the calculations.
With your TI950, do you have a CSM mode ? 
In the case of the pop-in toolbox, if i remember well, H and E are not used, only load displacement curves:
https://popin.readthedocs.io/en/latest/examples.html
In this  example, the mode CSM is not used and E or H are only calculated at max depth.
Thanks

**Comment by SUNLOVEERIN** [comment]
Hi,
That's true, the Pop-in tool doesn't need the H and E value of every point. As for your TriDimap toolbox, the data of H and E are necessary. I found some empirical equations to calculate H and E using displacement and load, as follows:
A=24.65hc^2
H=P/A
E=0.5(pi()^0.5)(1/A)(dP/dh)

Where, P means load, A means indentation area, hc means indentation depth.
I'm not sure this equation is correct or not, do you have any ideas?
Sincerely

**Comment by DavidMercier** [comment]
Hi, equations are right, but it depends on indenter tip and material rheology. For more information, you can look into this other toolbox and the doc : https://nims.readthedocs.io/en/latest/
You'll find models for conical indentation.
Good luck
